version: '3.8'
services:
  postgres_pc2:
    container_name: postgres_pc2
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pc2_db
    volumes:
      - ./pythonApp/init_script.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    networks:
      - app
  jupyter-notebook:
    image: continuumio/anaconda3
    command: jupyter notebook --port=8888 --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token='' --NotebookApp.password=''
    container_name: jupyter-notebook
    networks:
      - app
    depends_on:
      - postgres_pc2
    volumes:
      - ./notebooks:/notebooks
    ports:
      - 8888:8888
  dash:
    build: ./pythonApp
    depends_on:
      - postgres_pc2
    container_name: dash
    networks:
      - app
    ports:
      - 8060:8060
    environment:
      - VIRTUAL_HOST=dash.arthoughts.local
    restart: on-failure
networks:
  app:
    driver: bridge